config/routes.rb
Cyclic::Application.routes.draw do
  resources :rides

  resources :accounts do
    member do
      get 'invite'
      post 'send_invite'
    end
  end

  get "dashboard/index"

  devise_for :users

  resources :users

  root :to => 'dashboard#index'

end

app/models/ride.rb
class Ride < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :distance, :date
  validate :favourite_rides_must_have_a_name

  def favourite_rides_must_have_a_name
    if favourite && name.blank?
      errors.add(:name, "A favourite ride must have a name")
    end
  end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  load_and_authorize_resource

  # GET /rides
  # GET /rides.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rides }
    end
  end

  # GET /rides/1
  # GET /rides/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ride }
    end
  end

  # GET /rides/new
  # GET /rides/new.json
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ride }
    end
  end

  # GET /rides/1/edit
  def edit
  end

  # POST /rides
  # POST /rides.json
  def create
    respond_to do |format|
      if @ride.save
        format.html { redirect_to @ride, notice: 'Ride was successfully created.' }
        format.json { render json: @ride, status: :created, location: @ride }
      else
        format.html { render action: "new" }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rides/1
  # PUT /rides/1.json
  def update
    respond_to do |format|
      if @ride.update_attributes(params[:ride])
        format.html { redirect_to @ride, notice: 'Ride was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rides/1
  # DELETE /rides/1.json
  def destroy
    @ride.destroy

    respond_to do |format|
      format.html { redirect_to rides_url }
      format.json { head :ok }
    end
  end
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/views/rides/_form.html.erb
<%= form_for(@ride) do |f| %>
  <% if @ride.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ride.errors.count, "error") %> prohibited this ride from being saved:</h2>

      <ul>
      <% @ride.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :favourite %><br />
    <%= f.check_box :favourite %>
  </div>
  <div class="field">
    <%= f.label :distance %><br />
    <%= f.text_field :distance %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rides/edit.html.erb
<h1>Editing ride</h1>

<%= render 'form' %>

<%= link_to 'Show', @ride %> |
<%= link_to 'Back', rides_path %>

app/views/rides/index.html.erb
<h1>Listing rides</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Favourite</th>
    <th>Distance</th>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rides.each do |ride| %>
  <tr>
    <td><%= ride.name %></td>
    <td><%= ride.favourite %></td>
    <td><%= ride.distance %></td>
    <td><%= ride.date %></td>
    <td><%= link_to 'Show', ride %></td>
    <td><%= link_to 'Edit', edit_ride_path(ride) %></td>
    <td><%= link_to 'Destroy', ride, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ride', new_ride_path %>

app/views/rides/new.html.erb
<h1>New ride</h1>

<%= render 'form' %>

<%= link_to 'Back', rides_path %>

app/views/rides/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @ride.name %>
</p>

<p>
  <b>Favourite:</b>
  <%= @ride.favourite %>
</p>

<p>
  <b>Distance:</b>
  <%= @ride.distance %>
</p>

<p>
  <b>Date:</b>
  <%= @ride.date %>
</p>


<%= link_to 'Edit', edit_ride_path(@ride) %> |
<%= link_to 'Back', rides_path %>