config/routes.rb
Cyclic::Application.routes.draw do
  resources :rides

  resources :accounts do
    member do
      get 'invite'
      post 'send_invite'
    end
  end

  get "dashboard/index"

  devise_for :users

  resources :users

  root :to => 'dashboard#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cyclic</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="topbar-wrapper" style="z-index: 5;">
    <div class="topbar" data-dropdown="dropdown">
      <div class="topbar-inner">
        <div class="container">
          <h3><a href="/">Cyclic</a></h3>
          <% if user_signed_in? %>
            <ul class="nav">
              <li><%= link_to 'Rides', rides_path %></li>
            </ul>
            <ul class="nav secondary-nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle"><%= current_user %></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'My Profile', edit_user_path(current_user) %></li>
                  <li><%= link_to 'My Account', edit_account_path(current_user.account) %></li>
                  <li><%= link_to 'Send an invite', invite_account_path(current_user.account) %></li>
                  <li class="divider"></li>
                  <li><%= link_to 'Logout', destroy_user_session_path %></li>
                </ul>
              </li>
            </ul>
          <% end %>
          <% if !(user_signed_in?)  %>
            <ul class="nav secondary-nav">
              <li><%= link_to 'Login', new_user_session_path %></li>
            </ul>
          <% end %>
        </div>
      </div><!-- /topbar-inner -->
    </div><!-- /topbar -->
  </div>

  <div class="container">
    <% if notice %>
      <div class="alert-message warning"><%= notice %></div>
    <% end %>
    <% if alert %>
      <div class="alert-message error"><%= alert %></div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>