config/routes.rb
Cyclic::Application.routes.draw do
  resources :rides

  resources :accounts do
    member do
      get 'invite'
      post 'send_invite'
    end
  end

  get "dashboard/index"

  devise_for :users

  resources :users

  root :to => 'dashboard#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :users
  validates_presence_of :name
  validates :name, :uniqueness => true

  def to_s
    name
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  load_and_authorize_resource
  
  # GET /accounts/1
  # GET /accounts/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/1/edit
  def edit
  end

  def update
    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  def invite
    @user = User.new
  end

  def send_invite
    @user = User.new
    @user.email = params[:user][:email]
    @user.password = @user.password_confirmation = Devise.friendly_token
    @user.account = @account
    if @user.save
      redirect_to invite_account_url(@account), :notice => "#{@user.email} has been invited and should a confirmation email."
    else
      render :invite
    end
  end
    
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <fieldset>
    <%= f.twitter_text_field :name, :input => [ :class => 'xxlarge' ] %>
  </fieldset>
  <div class="actions">
    <%= f.submit "Update Account", class: 'btn primary' %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1><%= @account %> account administration</h1>

<%= render 'form' %>

app/views/accounts/invite.html.erb
<h2>Invite someone to join you at <%= @account %></h2>
<%= form_for @user, :url => send_invite_account_path(@account) do |f| %>
  <fieldset>
    <%= f.twitter_email_field :email %>
  </fieldset>
  <div class="actions">
    <%= f.submit 'Send Invite', class: "btn primary" %>
  </div>
<% end %>

app/views/accounts/show.html.erb
<h1><%= @account %></h1>

<div class="actions">
  <%= link_to 'Edit', edit_account_path(@account), :class => 'btn primary' %>
</div>